// Code generated by hertz generator.

package hello

import (
	"context"

	hello "hertz_demo/gen/model/hello"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Hello .
// @router /hello [GET]
func Hello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.HelloResp)

	c.JSON(consts.StatusOK, resp)
}

// World .
// @router /world [GET]
func World(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.WorldReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.WorldResp)

	c.JSON(consts.StatusOK, resp)
}
