// Code generated by hertz generator.

package hello

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _helloMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _worldMw() []app.HandlerFunc {
	// your code...
	return nil
}
