// Code generated by hertz generator.

package router

import (
	handler "hertz_demo/internal/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	registerSwagger(r)
}
